import Head from 'next/head'
import MainCard from '../src/components/MainCard'
import ShapesUp from '../src/components/ShapesUp'
import ShapesDown from '../src/components/ShapesDown'

import Image from 'next/image'

import { motion } from "framer-motion"
import {useRef} from 'react'

import Nav from '../src/components/Nav'
import About from '../src/components/About'
import Projects from '../src/components/Projects'
import Skills from '../src/components/Skills'
import Contact from '../src/components/Contact'

export default function Home() {

  const top = useRef(null)
  const executeScroll = () => top.current.scrollIntoView() 

  return (
    <div ref={top}>
      <Head>
        <title>Abigail Kaye Unating</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/aku.png" />
      </Head>

      <main>
            <ShapesUp/>
            <ShapesDown/>
        
            <Nav/>
        <div className="flex flex-col justify-center items-center gap-56 mb-64">
            <MainCard/>
            <Projects/>
            <About/>
            <Skills/>
            <Contact/>
        </div>
            
      </main>

      <footer className="p-10 px-2 md:px-32 z-10 relative glass shadow-none">
        <div className="flex justify-between">
          <p className="text-pink font-bold md:text-lg text-xs">2021 © aku.</p>
          <div className="flex gap-3 w-20 md:w-28">
            <a href="https://www.behance.net/abbyunat" target="_blank" rel="noreferrer" className="transform transition duration-500 ease-in-out hover:-translate-y-1.5"><Image src="/behance.svg" alt="" width="30" height="30"/></a>
            <a href="https://www.linkedin.com/in/abbyunat/" target="_blank" rel="noreferrer" className="transform transition duration-500 ease-in-out hover:-translate-y-1.5"><Image src="/linkedin.svg" alt="" width="30" height="30"/></a>
            <a href="https://github.com/keiruu" target="_blank" rel="noreferrer" className="transform transition duration-500 ease-in-out hover:-translate-y-1.5"><Image src="/github.svg" alt="" width="30" height="30"/></a>
          </div>
          <p className="text-pink font-bold cursor-pointer md:text-lg text-xs" onClick={executeScroll}>back to top.</p>
        </div>
      </footer>
    </div>
  )
}
